import { Member } from '../types';

export const MOCK_MEMBERS: Member[] = [
  {
    id: '1',
    email: 'joao@email.com',
    role: 'MEMBER',
    status: 'ACTIVE',
    firstName: 'João',
    lastName: 'Silva',
    cpf: '123.456.789-00',
    rg: '12.345.678-9',
    birthDate: '1990-05-15',
    naturalness: 'São Paulo-SP',
    nationality: 'Brasileiro(a)',
    maritalStatus: 'Casado',
    cep: '05107-000',
    address: 'Av. dos Remédios',
    number: '458',
    neighborhood: 'Vila dos Remédios',
    city: 'São Paulo',
    state: 'SP',
    phones: [],
    cell: '(11) 98765-4321',
    education: 'Superior',
    profession: 'Engenheiro',
    isBaptized: true,
    isHolySpiritBaptized: true,
    entryDate: '2010',
    participatesInConvention: false,
    receivedAs: 'MEMBRO',
    departments: ['Mídia'],
    leaderDepartment: '',
    consecratedTo: '',
    consecrationDate: '',
    currentPosition: 'Membro',
    positionStartDate: '2010-01-01',
    ministerialHistory: [
      {
        id: 'h1',
        type: 'OUTRO',
        description: 'Ingressou como Congregado',
        date: '2010-01-01',
        registeredBy: 'Sistema'
      },
      {
        id: 'h2',
        type: 'MUDANÇA_CARGO',
        description: 'Recebido como Membro',
        date: '2011-05-15',
        registeredBy: 'Secretaria'
      }
    ],
    validUntil: '2025-12-31',
    lastUpdated: '2024-02-24',
    hasChildren: true,
    children: [
      {
        name: 'Pedro Silva',
        cpf: '444.555.666-77',
        birthDate: '2015-10-10',
        congregates: 'Sim',
        departments: ['Departamento Infantil – Cordeirinhos']
      }
    ]
  },
  {
    id: '2',
    email: 'maria@email.com',
    role: 'SECRETARY',
    status: 'ACTIVE',
    firstName: 'Maria',
    lastName: 'Oliveira',
    cpf: '987.654.321-00',
    rg: '98.765.432-1',
    birthDate: '1985-08-20',
    naturalness: 'Rio de Janeiro-RJ',
    nationality: 'Brasileiro(a)',
    maritalStatus: 'Solteiro',
    cep: '05107-000',
    address: 'Av. dos Remédios',
    number: '458',
    neighborhood: 'Vila dos Remédios',
    city: 'São Paulo',
    state: 'SP',
    phones: [],
    cell: '(11) 99999-8888',
    education: 'Pós-graduação',
    profession: 'Administradora',
    isBaptized: true,
    isHolySpiritBaptized: true,
    entryDate: '2015',
    participatesInConvention: true,
    conventionName: 'CONFRADESP',
    receivedAs: 'MEMBRO',
    departments: ['Secretariado', 'Departamento Irmãs - Rosas de Saron'],
    leaderDepartment: 'Secretariado',
    consecratedTo: 'Missionária',
    consecrationDate: '2020-10-10',
    currentPosition: 'Missionária',
    positionStartDate: '2020-10-10',
    ministerialHistory: [],
    validUntil: '2025-12-31',
    lastUpdated: '2024-02-24',
    hasChildren: false
  },
  {
    id: '3',
    email: 'admin@familia.com',
    role: 'ADMIN',
    status: 'ACTIVE',
    firstName: 'Pastor',
    lastName: 'Carlos',
    cpf: '111.222.333-44',
    rg: '11.222.333-4',
    birthDate: '1970-01-01',
    naturalness: 'São Paulo-SP',
    nationality: 'Brasileiro(a)',
    maritalStatus: 'Casado',
    cep: '05107-000',
    address: 'Av. dos Remédios',
    number: '458',
    neighborhood: 'Vila dos Remédios',
    city: 'São Paulo',
    state: 'SP',
    phones: [],
    cell: '(11) 91111-2222',
    education: 'Teologia',
    profession: 'Pastor',
    isBaptized: true,
    isHolySpiritBaptized: true,
    entryDate: '2000',
    participatesInConvention: true,
    conventionName: 'CGADB',
    receivedAs: 'MEMBRO',
    departments: ['Departamento de Líderes', 'Departamento de Obreiros (Cooperadores)'],
    leaderDepartment: 'Departamento de Líderes',
    consecratedTo: 'Pastor',
    consecrationDate: '2005-05-05',
    currentPosition: 'Pastor',
    positionStartDate: '2005-05-05',
    ministerialHistory: [],
    validUntil: '2026-12-31',
    lastUpdated: '2024-02-24',
    hasChildren: true,
    children: [
      {
        name: 'Ana Carlos',
        cpf: '777.888.999-00',
        birthDate: '2010-05-05',
        congregates: 'Sim',
        departments: ['Departamento da Adolescência']
      }
    ]
  }
];
